/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7gDl3KQt14t
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from '@/components/ui/button';
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerTitle,
  DrawerTrigger,
} from '@/components/ui/drawer';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

export function BottomSheet() {
  return (
    <div className='navbar fixed bottom-24 left-1/2 z-50 -translate-x-1/2'>
      <Drawer defaultOpen>
        <DrawerTrigger asChild>
          <Button
            variant='outline'
            className='w-1/2 rounded-full'
            // className='navbar fixed bottom-4 left-1/2 z-50 -translate-x-1/2'
          >
            목록보기
          </Button>
        </DrawerTrigger>
        {/* <div className='navbar fixed'> */}
        <DrawerContent className='customWidth rounded-t-2xl bg-black/20 bg-white p-6 shadow-2xl dark:bg-gray-950'>
          <div className='mb-6 flex items-center justify-between'>
            <DrawerTitle className='text-2xl font-bold'>
              Bottom Sheet
            </DrawerTitle>
            <DrawerClose asChild>
              <Button variant='ghost' size='icon'>
                <XIcon className='h-6 w-6' />
              </Button>
            </DrawerClose>
          </div>
          <div className='space-y-4'>
            <div>
              <Label htmlFor='name'>Name</Label>
              <Input id='name' placeholder='Enter your name' />
            </div>
            <div>
              <Label htmlFor='email'>Email</Label>
              <Input id='email' type='email' placeholder='Enter your email' />
            </div>
            <div>
              <Label htmlFor='message'>Message</Label>
              <Textarea
                id='message'
                placeholder='Enter your message'
                rows={4}
              />
            </div>
            <Button type='submit'>Submit</Button>
          </div>
        </DrawerContent>
        {/* </div> */}
      </Drawer>
    </div>
  );
}

function XIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M18 6 6 18' />
      <path d='m6 6 12 12' />
    </svg>
  );
}
