name: Main Server Merge
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v3

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      # - name: Set .env from secrets
      #   run: |
      #     echo "${{ secrets.MAIN_ENV }}" > .env
      # - name: cat env file
      #   run: cat .env

      - name: Install dependencies # 의존 파일 설치
        run: pnpm install

      - name: Generate wbuild # React Build
        run: pnpm build
